name: Hello,World!
on: pull_request

jobs:
  github-context:
    name: GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

jobs:
  if-pull-request-is-opened:
    name: If
    runs-on: ubuntu-latest
    steps:
      - name: echo if pull request is opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: echo "pull request is opened"

jobs:
  job1:
    name: Greeting 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello,World 1"

jobs:
  job2:
    name: Greeting 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello,World 2"

jobs:
  job3:
    name: Greeting 3
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello,World 3"

jobs:
  Build:
    name: Greeting on Name
    needs: [job2, job3]
    runs-on: ubuntu-latest
    steps:
      - env:
          NAME: MONA
      - run: echo "Hello, ${NAME}"
